[build]
target-dir = "target"

[env]
OPENSSL_DIR = "C:\\Program Files\\OpenSSL-Win64"
OPENSSL_LIB_DIR = "C:\\Program Files\\OpenSSL-Win64\\lib\\VC\\x64\\MD"
OPENSSL_INCLUDE_DIR = "C:\\Program Files\\OpenSSL-Win64\\include"
